name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up local.properties
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      - name: Set up keystore
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_DEBUG_BASE64 }}" | base64 -d > keystore/debug.keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore/release.jks
          echo "KEYSTORE_STORE_PASSWORD=${{ secrets.KEYSTORE_STORE_PASSWORD }}" >> local.properties
          echo "KEYSTORE_ALIAS=${{ secrets.KEYSTORE_ALIAS }}" >> local.properties
          echo "KEYSTORE_KEY_PASSWORD=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> local.properties
          echo "NDGL_BASE_URL_DEBUG=${{ secrets.NDGL_BASE_URL_DEBUG }}" >> local.properties
          echo "NDGL_BASE_URL_RELEASE=${{ secrets.NDGL_BASE_URL_RELEASE }}" >> local.properties

      - name: Set up google-services.json
        run: |
          mkdir -p app/src/debug app/src/release
          echo '${{ secrets.GOOGLE_SERVICES_DEBUG }}' | base64 -d > app/src/debug/google-services.json
          echo '${{ secrets.GOOGLE_SERVICES_RELEASE }}' | base64 -d > app/src/release/google-services.json

      - name: Upload config files
        uses: actions/upload-artifact@v4
        with:
          name: config-files
          retention-days: 1
          path: |
            local.properties
            keystore/debug.keystore
            keystore/release.jks
            app/src/debug/google-services.json
            app/src/release/google-services.json

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup

      - name: Code style checks
        run: ./gradlew ktlintCheck detekt --build-cache --parallel

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup

      - name: Run build
        run: ./gradlew assembleDebug --build-cache --parallel --stacktrace
